pb_file: "./yolov3_coco.pb"
return_elements: ["input/input_data:0", "pred_sbbox/concat_2:0", "pred_mbbox/concat_2:0", "pred_lbbox/concat_2:0"]
num_classes: 80            #person=0，bike=1, car=2, motobike=3, truck=7
input_size: 640
alarm_range: 6
camera_no: "01" # 01~48
obj_dict: {0: ['人',0], 1: ['非机动车',1,3], 2: ['汽车',2,5,7]}
mask_dict: {0: '可停车区域', 1: '不可停车区域'}


detect_interval: 3

url: "http://www.xxxxx/myweb/request"
